### ISSUE TITLE
Typescript 5

### ISSUE THREAD

**Issue by trainiac** [voodoocreation/ts-deepmerge#24]
Currently the library is pinned to `"typescript": "^4.9.4"`.  Can we upgrade the dep to allow for 5?

**Comment by voodoocreation** [comment]
I just saw your PR, but I'll do a full round of dependency updates soon before releasing a new version - sorry it's taken a couple of days to get to this.

Are you running into issues in your project? Just wondering, because `typescript` is only in our `devDependencies` rather than `peerDependencies` or `dependencies`, so it shouldn't be impacting things in consumers' projects - it's designed so that it _should_ just allow you to use whichever version of TS you wish.

**Comment by voodoocreation** [comment]
Version `6.0.3` is up now, though because there were only changes to `devDependencies`, there should be no functional changes to the package.
