### ISSUE TITLE
Deep merge of classes with private properties

### ISSUE THREAD

**Issue by thyming** [voodoocreation/ts-deepmerge#29]
Hi, I'm encountering an issue when merging objects that have ES6-class-valued properties that have private properties on them. An example:
```typescript
class A {
  constructor(private readonly b: number) {}
}

interface C {
  a: A;
}

const d: C = merge({ a: new A(1) }, { a: new A(2) });
```
This example does not compile with typescript 5.1.6, @tsconfig/node20/tsconfig.json, and ts-deepmerge > 4.0.0 (it works <= 4.0.0).
I can see both sides of this being a bug or not - curious what you think. If you don't consider this a bug, do you have any ideas about a workaround?

**Comment by voodoocreation** [comment]
Hey, unfortunately this package is only designed to merge simple object primitives, rather than class instances like you're attempting to merge here. If you try to merge class instances you'll encounter problems due to their more complex nature. The most I would consider doing is potentially trying to update the logic so that it will simply replace the property altogether with the latest one, but it could be tricky due to how the object detection works.

Depending on what you're trying to achieve though, it may be simpler to just use the spread operator to merge things manually so that you can be more explicit about how you'd like things to merge.

**Comment by thyming** [comment]
Yeah, that's what I figured, thanks for the response and the great library!
