### ISSUE TITLE
Merge to eliminate optionals

### ISSUE THREAD

**Issue by thany** [voodoocreation/ts-deepmerge#30]
Consider this snippet:

```typescript
interface Foo {
  x: number;
  y: number;
}

const a: Foo = { x: 1, y: 2 };
const b: Partial<Foo> = { x: 3 };

const merged = merge(a, b);
```

In this snippet, I would expect the values to get merged. They are. So far so good. But I would expect the same for the types. Merging a required and optional member of the same name, should result in that type becoming a required one. That is, among others, what I think merging types should be about.

It should be more than just simply "orring" them together.

**Comment by thany** [comment]
To be perfectly honest, I also wouldn't know how to merge types like that. I'm pretty sure it's possible though, perhaps through [Narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) or a similar mechanism.

**Comment by voodoocreation** [comment]
Yeah it's quite a tricky one - especially to get the types to be more aware of all the logic that happens when merging in the runtime code, as well as the various options. This is why the types work as they do currently as a sort of "best guess", referencing all possible types from the merge. You can have a look at how the types work [here](https://github.com/voodoocreation/ts-deepmerge/blob/master/index.ts#L1-L31) for context.

I'll leave this issue open for now in case anyone would like to open a PR to address it, so that there's this discoverable context around it.

To work around it though in use cases where you're working with declared types and have the awareness of what it will actually output, I'd definitely recommend using the `merge(a, b, c) as MyDeclaredType;` syntax so that you can still make use of the deep merge functionality 🙏

**Comment by voodoocreation** [comment]
Actually, I've just added this context to the readme file and linked to this issue, so will close this issue for now, as I'm still not aware of a way for the type inferring to work as described here while still allowing an infinite number of args, as type narrowing is more for inferring the return type from the runtime logic, which isn't how `ts-deepmerge` performs the return type inferring due to the limitations that has.
